apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:tgocrbhgBZj3AsNtf+c0Trny+ku401RuTB4FequlVKERXh3GLxSGIATKky7WFhbhBjaucDwMy9LUgWMC,iv:KorIHKJtKSy5DnE31ZlgQNswKyQcWbqIk763rqh/rVk=,tag:s7G6z6VR05dmjpSn5zXPYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sens6q7vmpr3339ffmgff686r5gkmzmmg9wkns6f9ltae7lked7swvq6aw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTTBUTjdkUGdUOG5uUXd5
            STNGbUZkUzdyZG14VjlkMy90NkRCYzcwVjNZCmlrUkExR1hFOEVNNHJZRTFGMFEr
            VDVqYXk3dFZsMG5yM3BFTjRsa09yS0kKLS0tIGtMTjIveGtFYmlhZEg5ZHdZbXlo
            RG9OQ3JQRGJRYzlBLzBSNkdDWDMweGMKEUCpOyWkzkaq7y8s2fC3zdHJNoGha4zY
            BVxCk6RrIWdYhyqc7nT1JzVSjv153VbCvyZ3ncI01y0kSUoVeVsE+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T16:19:03Z"
    mac: ENC[AES256_GCM,data:tcUJ310boB9oERC2j7spXKSB6covbNWY4pSwp9HQkhQltDaz3U7KCVnj+AbVvVPGPQ2owe1Dn8Oc26+4zq9QLcCR6LHgqqk56etWj5n0UJ9dKHLGYq8bd8g9gblhFr/6rk9v8JNdEBV6GUo6tc2jCUEDaHaHHY2vK4wp/UkP2nI=,iv:87d0uY2Du9SXb4LhJ4taQrkLFnmEWFz2W8g1zqFT3oo=,tag:Oexg8Ao8TIIalrk3/fdUDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
